### ISSUE TITLE
How to use only Interpreter?

### ISSUE THREAD

**Issue by shlifedev** [imagicbell/ublockly#32]
First thanks, this project is very great! But I want use interpreter only..  
(I want to use the xml I created from my blockly web site.)

Can you make a simple example or tips?

**Comment by imagicbell** [comment]
There are APIs for parsing xml in [Xml.cs](https://github.com/imagicbell/ublockly/blob/master/Source/Script/Core/Xml.cs)
```
TextToDom(string text) {}
DomToWorkspace(XmlNode xml, Workspace workspace) {}
```
You can also follow this code to load XML, in [XmlView.cs](https://github.com/imagicbell/ublockly/blob/master/Source/Script/UGUIView/XmlView.cs)
```
LoadXml(string fileName) {}
```
There might be some incompatible errors because my XML structure might not be 100% the same as google blockly.

**Comment by shlifedev** [comment]
Thanks! (❁´◡`❁)❤
